# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './../designer/MainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormMainWindow(object):
    def setupUi(self, FormMainWindow):
        FormMainWindow.setObjectName("FormMainWindow")
        FormMainWindow.resize(1000, 600)
        FormMainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormMainWindow)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetMain = QtWidgets.QWidget(FormMainWindow)
        self.widgetMain.setObjectName("widgetMain")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetMain)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widgetTitlebar = QtWidgets.QWidget(self.widgetMain)
        self.widgetTitlebar.setObjectName("widgetTitlebar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetTitlebar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.tips_wg = QtWidgets.QWidget(self.widgetTitlebar)
        self.tips_wg.setEnabled(True)
        self.tips_wg.setMinimumSize(QtCore.QSize(600, 30))
        self.tips_wg.setMaximumSize(QtCore.QSize(600, 16777215))
        self.tips_wg.setSizeIncrement(QtCore.QSize(600, 30))
        self.tips_wg.setBaseSize(QtCore.QSize(600, 30))
        self.tips_wg.setStyleSheet("")
        self.tips_wg.setObjectName("tips_wg")
        self.horizontalLayout.addWidget(self.tips_wg)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonSkin = QtWidgets.QPushButton(self.widgetTitlebar)
        self.buttonSkin.setText("")
        self.buttonSkin.setObjectName("buttonSkin")
        self.horizontalLayout.addWidget(self.buttonSkin)
        self.buttonIssues = QtWidgets.QPushButton(self.widgetTitlebar)
        self.buttonIssues.setText("")
        self.buttonIssues.setObjectName("buttonIssues")
        self.horizontalLayout.addWidget(self.buttonIssues)
        self.buttonMinimum = QtWidgets.QPushButton(self.widgetTitlebar)
        self.buttonMinimum.setText("")
        self.buttonMinimum.setObjectName("buttonMinimum")
        self.horizontalLayout.addWidget(self.buttonMinimum)
        self.buttonMaximum = QtWidgets.QPushButton(self.widgetTitlebar)
        self.buttonMaximum.setText("")
        self.buttonMaximum.setObjectName("buttonMaximum")
        self.horizontalLayout.addWidget(self.buttonMaximum)
        self.buttonNormal = QtWidgets.QPushButton(self.widgetTitlebar)
        self.buttonNormal.setText("")
        self.buttonNormal.setObjectName("buttonNormal")
        self.horizontalLayout.addWidget(self.buttonNormal)
        self.buttonClose = QtWidgets.QPushButton(self.widgetTitlebar)
        self.buttonClose.setText("")
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout.addWidget(self.buttonClose)
        self.verticalLayout_2.addWidget(self.widgetTitlebar)
        self.widgetCentral = QtWidgets.QWidget(self.widgetMain)
        self.widgetCentral.setObjectName("widgetCentral")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetCentral)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widgetCatalogs = WaterWidget(self.widgetCentral)
        self.widgetCatalogs.setObjectName("widgetCatalogs")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widgetCatalogs)
        self.verticalLayout_4.setContentsMargins(20, 30, 20, 30)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widgetHead = QtWidgets.QWidget(self.widgetCatalogs)
        self.widgetHead.setObjectName("widgetHead")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widgetHead)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.buttonHead = RotateButton(self.widgetHead)
        self.buttonHead.setText("")
        self.buttonHead.setObjectName("buttonHead")
        self.horizontalLayout_4.addWidget(self.buttonHead)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_4.addWidget(self.widgetHead)
        self.widgetSearch = QtWidgets.QWidget(self.widgetCatalogs)
        self.widgetSearch.setObjectName("widgetSearch")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widgetSearch)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.basicmsg = QtWidgets.QTextEdit(self.widgetSearch)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.basicmsg.setFont(font)
        self.basicmsg.setStyleSheet("")
        self.basicmsg.setAcceptRichText(True)
        self.basicmsg.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.basicmsg.setObjectName("basicmsg")
        self.verticalLayout_6.addWidget(self.basicmsg)
        self.verticalLayout_4.addWidget(self.widgetSearch)
        self.horizontalLayout_2.addWidget(self.widgetCatalogs)
        self.widgetTools = QtWidgets.QWidget(self.widgetCentral)
        self.widgetTools.setObjectName("widgetTools")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widgetTools)
        self.verticalLayout_5.setContentsMargins(12, 35, 12, 30)
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.buttonGithub = RotateButton(self.widgetTools)
        self.buttonGithub.setText("")
        self.buttonGithub.setObjectName("buttonGithub")
        self.verticalLayout_5.addWidget(self.buttonGithub)
        self.buttonQQ = RotateButton(self.widgetTools)
        self.buttonQQ.setText("")
        self.buttonQQ.setObjectName("buttonQQ")
        self.verticalLayout_5.addWidget(self.buttonQQ)
        self.buttonGroup = RotateButton(self.widgetTools)
        self.buttonGroup.setText("")
        self.buttonGroup.setObjectName("buttonGroup")
        self.verticalLayout_5.addWidget(self.buttonGroup)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.buttonHome = RubberBandButton(self.widgetTools)
        self.buttonHome.setText("")
        self.buttonHome.setObjectName("buttonHome")
        self.verticalLayout_5.addWidget(self.buttonHome)
        self.buttonBackToUp = RubberBandButton(self.widgetTools)
        self.buttonBackToUp.setText("")
        self.buttonBackToUp.setObjectName("buttonBackToUp")
        self.verticalLayout_5.addWidget(self.buttonBackToUp)
        self.horizontalLayout_2.addWidget(self.widgetTools)
        self.widgetContents = QtWidgets.QWidget(self.widgetCentral)
        self.widgetContents.setObjectName("widgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widgetContents)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.snake = QtWidgets.QWidget(self.widgetContents)
        self.snake.setStyleSheet("")
        self.snake.setObjectName("snake")
        self.pyqtgraph1 = GraphicsLayoutWidget(self.snake)
        self.pyqtgraph1.setGeometry(QtCore.QRect(0, 0, 674, 201))
        self.pyqtgraph1.setObjectName("pyqtgraph1")
        self.pyqtgraph2 = GraphicsLayoutWidget(self.snake)
        self.pyqtgraph2.setGeometry(QtCore.QRect(0, 210, 674, 351))
        self.pyqtgraph2.setObjectName("pyqtgraph2")
        self.verticalLayout_3.addWidget(self.snake)
        self.web = QtWidgets.QWidget(self.widgetContents)
        self.web.setStyleSheet("")
        self.web.setObjectName("web")
        self.verticalLayout_3.addWidget(self.web)
        self.tetris = QtWidgets.QWidget(self.widgetContents)
        self.tetris.setEnabled(True)
        self.tetris.setMinimumSize(QtCore.QSize(500, 0))
        self.tetris.setBaseSize(QtCore.QSize(100, 0))
        self.tetris.setStyleSheet("")
        self.tetris.setObjectName("tetris")
        self.frame = QtWidgets.QFrame(self.tetris)
        self.frame.setGeometry(QtCore.QRect(350, 90, 180, 380))
        self.frame.setMinimumSize(QtCore.QSize(180, 380))
        self.frame.setMaximumSize(QtCore.QSize(180, 379))
        self.frame.setSizeIncrement(QtCore.QSize(180, 380))
        self.frame.setStyleSheet("\n"
"background-color: rgba(255, 255, 255, 180);\n"
"border-style:outset;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.tetris)
        self.lineEdit.setGeometry(QtCore.QRect(100, 170, 141, 21))
        self.lineEdit.setStyleSheet("border-color: rgba(255, 255, 255, 0);\n"
"border-style:outset;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tetris)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 200, 141, 21))
        self.lineEdit_2.setStyleSheet("border-color: rgba(255, 255, 255, 0);\n"
"border-style:outset;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tetris)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 230, 141, 21))
        self.lineEdit_3.setStyleSheet("border-color: rgba(255, 255, 255, 0);\n"
"border-style:outset;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tetris)
        self.lineEdit_4.setGeometry(QtCore.QRect(100, 260, 141, 21))
        self.lineEdit_4.setStyleSheet("border-color: rgba(255, 255, 255, 0);\n"
"border-style:outset;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tetris)
        self.lineEdit_5.setEnabled(True)
        self.lineEdit_5.setGeometry(QtCore.QRect(100, 290, 141, 21))
        self.lineEdit_5.setMouseTracking(False)
        self.lineEdit_5.setAcceptDrops(False)
        self.lineEdit_5.setStyleSheet("border-color: rgba(255, 255, 255, 0);\n"
"border-style:outset;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tetris)
        self.lineEdit_6.setGeometry(QtCore.QRect(100, 140, 161, 21))
        self.lineEdit_6.setStyleSheet("border-color: rgba(255, 255, 255, 0);\n"
"border-style:outset;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit_6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_3.addWidget(self.tetris)
        self.horizontalLayout_2.addWidget(self.widgetContents)
        self.verticalLayout_2.addWidget(self.widgetCentral)
        self.verticalLayout.addWidget(self.widgetMain)

        self.retranslateUi(FormMainWindow)
        QtCore.QMetaObject.connectSlotsByName(FormMainWindow)

    def retranslateUi(self, FormMainWindow):
        _translate = QtCore.QCoreApplication.translate
        FormMainWindow.setWindowTitle(_translate("FormMainWindow", "PyQtClient"))
        self.buttonGithub.setToolTip(_translate("FormMainWindow", "Project Url"))
        self.buttonQQ.setToolTip(_translate("FormMainWindow", "Tetris"))
        self.buttonGroup.setToolTip(_translate("FormMainWindow", "Data Parse"))
        self.buttonHome.setToolTip(_translate("FormMainWindow", "Home Page"))
        self.buttonBackToUp.setToolTip(_translate("FormMainWindow", "Back to Top"))
        self.lineEdit.setText(_translate("FormMainWindow", "P      键：  暂停|恢复"))
        self.lineEdit_2.setText(_translate("FormMainWindow", "空格键：   加速"))
        self.lineEdit_3.setText(_translate("FormMainWindow", "上    键：   逆时针旋转"))
        self.lineEdit_4.setText(_translate("FormMainWindow", "左    键：   左移"))
        self.lineEdit_5.setText(_translate("FormMainWindow", "上    键：   顺时针旋转"))
        self.lineEdit_6.setText(_translate("FormMainWindow", "点击游戏区域按P键玩游戏"))

from Widgets.Buttons.RotateButton import RotateButton
from Widgets.Buttons.RubberBandButton import RubberBandButton
from Widgets.WaterWidget import WaterWidget
from pyqtgraph import GraphicsLayoutWidget
